### ISSUE TITLE
Chaincode installation error

### ISSUE THREAD

**Issue by Sumanarayan** [HyperledgerHandsOn/trade-finance-logistics#58]
Hi,
While installing the chaincode , we are facing the below issue.
COMMAND:::
$node createTradeApp.js

BELOW IS THE ERROR:::::::
info: [ClientUtils]: 

*******************************************************************************
*******************************************************************************
*                                          
* Using temp dir: ../network/client-certs
*                                          
*******************************************************************************
*******************************************************************************

(node:14685) DeprecationWarning: grpc.load: Use the @grpc/proto-loader module with grpc.loadPackageDefinition instead
Successfully extracted the config update from the configtx envelope
Successfully enrolled user 'admin' for exporterorg
Successfully signed config as admin of exporterorg
Successfully enrolled user 'admin' for importerorg
Successfully signed config as admin of importerorg
Successfully enrolled user 'admin' for carrierorg
Successfully signed config as admin of carrierorg
Successfully enrolled user 'admin' for regulatororg
Successfully signed config as admin of regulatororg
Successfully enrolled user 'admin' for every org and obtained channel config signatures
Successfully enrolled user 'admin' for orderer
error: [Orderer.js]: sendDeliver - rejecting - status:NOT_FOUND
Channel tradechannel does not exist yet (IGNORE ANY ORDERER ERROR MESSAGES YOU SEE ABOVE!!)
Successfully signed config update as orderer admin
Successfully created the channel.
Successfully waited to make sure new channel was created.

--------------------------
CHANNEL CREATION COMPLETE
--------------------------

Joining channel tradechannel
Successfully enrolled 'admin' user for org exporterorg
Successfully got the genesis block
TypeError: Cannot read property 'getConnectivityState' of undefined
    at EventHub._checkConnection (/home/hp/go/src/github.com/hyperledger/fabric/middleware/node_modules/fabric-client/lib/EventHub.js:479:39)
    at EventHub.registerBlockEvent (/home/hp/go/src/github.com/hyperledger/fabric/middleware/node_modules/fabric-client/lib/EventHub.js:658:8)
    at Promise (/home/hp/go/src/github.com/hyperledger/fabric/middleware/join-channel.js:161:8)
    at new Promise (<anonymous>)
    at eventhubs.forEach (/home/hp/go/src/github.com/hyperledger/fabric/middleware/join-channel.js:158:20)
    at Array.forEach (<anonymous>)
    at Client.newDefaultKeyValueStore.then.then.then (/home/hp/go/src/github.com/hyperledger/fabric/middleware/join-channel.js:157:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
Joining channel tradechannel
E0301 14:10:47.422452275   14685 ssl_transport_security.cc:1233] Handshake failed with fatal error SSL_ERROR_SSL: error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number.
E0301 14:10:47.422647044   14685 ssl_transport_security.cc:1233] Handshake failed with fatal error SSL_ERROR_SSL: error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number.
TypeError: Cannot read property 'getConnectivityState' of undefined
    at ClientDuplexStream.<anonymous> (/home/hp/go/src/github.com/hyperledger/fabric/middleware/node_modules/fabric-client/lib/EventHub.js:355:56)
    at emitOne (events.js:116:13)
    at ClientDuplexStream.emit (events.js:211:7)
    at ClientDuplexStream._emitStatusIfDone (/home/hp/go/src/github.com/hyperledger/fabric/middleware/node_modules/grpc/src/client.js:234:12)
    at ClientDuplexStream._receiveStatus (/home/hp/go/src/github.com/hyperledger/fabric/middleware/node_modules/grpc/src/client.js:211:8)
    at Object.onReceiveStatus (/home/hp/go/src/github.com/hyperledger/fabric/middleware/node_modules/grpc/src/client_interceptors.js:1306:15)
    at InterceptingListener._callNext (/home/hp/go/src/github.com/hyperledger/fabric/middleware/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/home/hp/go/src/github.com/hyperledger/fabric/middleware/node_modules/grpc/src/client_interceptors.js:618:8)
    at /home/hp/go/src/github.com/hyperledger/fabric/middleware/node_modules/grpc/src/client_interceptors.js:1123:18
error: [client-utils.js]: sendPeersProposal - Promise is rejected: Error: 14 UNAVAILABLE: Connect Failed
    at Object.exports.createStatusError (/home/hp/go/src/github.com/hyperledger/fabric/middleware/node_modules/grpc/src/common.js:91:15)
    at Object.onReceiveStatus (/home/hp/go/src/github.com/hyperledger/fabric/middleware/node_modules/grpc/src/client_interceptors.js:1204:28)
    at InterceptingListener._callNext (/home/hp/go/src/github.com/hyperledger/fabric/middleware/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/home/hp/go/src/github.com/hyperledger/fabric/middleware/node_modules/grpc/src/client_interceptors.js:618:8)
    at callback (/home/hp/go/src/github.com/hyperledger/fabric/middleware/node_modules/grpc/src/client_interceptors.js:845:24)
Successfully enrolled 'admin' user for org importerorg
Successfully got the genesis block
TypeError: Cannot read property 'getConnectivityState' of undefined
    at EventHub._checkConnection (/home/hp/go/src/github.com/hyperledger/fabric/middleware/node_modules/fabric-client/lib/EventHub.js:479:39)
    at EventHub.registerBlockEvent (/home/hp/go/src/github.com/hyperledger/fabric/middleware/node_modules/fabric-client/lib/EventHub.js:658:8)
    at Promise (/home/hp/go/src/github.com/hyperledger/fabric/middleware/join-channel.js:161:8)
    at new Promise (<anonymous>)
    at eventhubs.forEach (/home/hp/go/src/github.com/hyperledger/fabric/middleware/join-channel.js:158:20)
    at Array.forEach (<anonymous>)
    at Client.newDefaultKeyValueStore.then.then.then (/home/hp/go/src/github.com/hyperledger/fabric/middleware/join-channel.js:157:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
Joining channel tradechannel
TypeError: Cannot read property 'getConnectivityState' of undefined
    at ClientDuplexStream.<anonymous> (/home/hp/go/src/github.com/hyperledger/fabric/middleware/node_modules/fabric-client/lib/EventHub.js:308:56)
    at emitOne (events.js:116:13)
    at ClientDuplexStream.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at ClientDuplexStream.Readable.push (_stream_readable.js:208:10)
    at Object.onReceiveMessage (/home/hp/go/src/github.com/hyperledger/fabric/middleware/node_modules/grpc/src/client_interceptors.js:1292:19)
    at InterceptingListener.recvMessageWithContext (/home/hp/go/src/github.com/hyperledger/fabric/middleware/node_modules/grpc/src/client_interceptors.js:607:19)
    at /home/hp/go/src/github.com/hyperledger/fabric/middleware/node_modules/grpc/src/client_interceptors.js:706:14
Successfully enrolled 'admin' user for org carrierorg
Successfully got the genesis block
TypeError: Cannot read property 'getConnectivityState' of undefined
    at EventHub._checkConnection (/home/hp/go/src/github.com/hyperledger/fabric/middleware/node_modules/fabric-client/lib/EventHub.js:479:39)
    at EventHub.registerBlockEvent (/home/hp/go/src/github.com/hyperledger/fabric/middleware/node_modules/fabric-client/lib/EventHub.js:658:8)
    at Promise (/home/hp/go/src/github.com/hyperledger/fabric/middleware/join-channel.js:161:8)
    at new Promise (<anonymous>)
    at eventhubs.forEach (/home/hp/go/src/github.com/hyperledger/fabric/middleware/join-channel.js:158:20)
    at Array.forEach (<anonymous>)
    at Client.newDefaultKeyValueStore.then.then.then (/home/hp/go/src/github.com/hyperledger/fabric/middleware/join-channel.js:157:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
Joining channel tradechannel
Successfully enrolled 'admin' user for org regulatororg
TypeError: Cannot read property 'getConnectivityState' of undefined
    at ClientDuplexStream.<anonymous> (/home/hp/go/src/github.com/hyperledger/fabric/middleware/node_modules/fabric-client/lib/EventHub.js:308:56)
    at emitOne (events.js:116:13)
    at ClientDuplexStream.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at ClientDuplexStream.Readable.push (_stream_readable.js:208:10)
    at Object.onReceiveMessage (/home/hp/go/src/github.com/hyperledger/fabric/middleware/node_modules/grpc/src/client_interceptors.js:1292:19)
    at InterceptingListener.recvMessageWithContext (/home/hp/go/src/github.com/hyperledger/fabric/middleware/node_modules/grpc/src/client_interceptors.js:607:19)
    at /home/hp/go/src/github.com/hyperledger/fabric/middleware/node_modules/grpc/src/client_interceptors.js:706:14
Successfully got the genesis block
TypeError: Cannot read property 'getConnectivityState' of undefined
    at EventHub._checkConnection (/home/hp/go/src/github.com/hyperledger/fabric/middleware/node_modules/fabric-client/lib/EventHub.js:479:39)
    at EventHub.registerBlockEvent (/home/hp/go/src/github.com/hyperledger/fabric/middleware/node_modules/fabric-client/lib/EventHub.js:658:8)
    at Promise (/home/hp/go/src/github.com/hyperledger/fabric/middleware/join-channel.js:161:8)
    at new Promise (<anonymous>)
    at eventhubs.forEach (/home/hp/go/src/github.com/hyperledger/fabric/middleware/join-channel.js:158:20)
    at Array.forEach (<anonymous>)
    at Client.newDefaultKeyValueStore.then.then.then (/home/hp/go/src/github.com/hyperledger/fabric/middleware/join-channel.js:157:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)

----------------------
CHANNEL JOIN COMPLETE
----------------------

TypeError: Cannot read property 'getConnectivityState' of undefined
    at ClientDuplexStream.<anonymous> (/home/hp/go/src/github.com/hyperledger/fabric/middleware/node_modules/fabric-client/lib/EventHub.js:308:56)
    at emitOne (events.js:116:13)
    at ClientDuplexStream.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at ClientDuplexStream.Readable.push (_stream_readable.js:208:10)
    at Object.onReceiveMessage (/home/hp/go/src/github.com/hyperledger/fabric/middleware/node_modules/grpc/src/client_interceptors.js:1292:19)
    at InterceptingListener.recvMessageWithContext (/home/hp/go/src/github.com/hyperledger/fabric/middleware/node_modules/grpc/src/client_interceptors.js:607:19)
    at /home/hp/go/src/github.com/hyperledger/fabric/middleware/node_modules/grpc/src/client_interceptors.js:706:14
Successfully enrolled user 'admin'
info: [packager/Golang.js]: packaging GOLANG from github.com/trade_workflow
E0301 14:10:48.467319812   14685 ssl_transport_security.cc:1233] Handshake failed with fatal error SSL_ERROR_SSL: error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number.
error: [client-utils.js]: sendPeersProposal - Promise is rejected: Error: 14 UNAVAILABLE: Connect Failed
    at Object.exports.createStatusError (/home/hp/go/src/github.com/hyperledger/fabric/middleware/node_modules/grpc/src/common.js:91:15)
    at Object.onReceiveStatus (/home/hp/go/src/github.com/hyperledger/fabric/middleware/node_modules/grpc/src/client_interceptors.js:1204:28)
    at InterceptingListener._callNext (/home/hp/go/src/github.com/hyperledger/fabric/middleware/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/home/hp/go/src/github.com/hyperledger/fabric/middleware/node_modules/grpc/src/client_interceptors.js:618:8)
    at callback (/home/hp/go/src/github.com/hyperledger/fabric/middleware/node_modules/grpc/src/client_interceptors.js:845:24)
error: [install-chaincode]: install proposal was bad from peer grpcs://localhost:7051 in org exporterorg
Failed to install chaincode in peers of organization "exporterorg". Error: Failed to send install Proposal or receive valid response from org exporterorg: Error: 14 UNAVAILABLE: Connect Failed
    at Client.newDefaultKeyValueStore.then.then.then (/home/hp/go/src/github.com/hyperledger/fabric/middleware/install-chaincode.js:136:10)
    at <anonymous>
error: [install-chaincode]: Failed to install chaincode in peers of organization "exporterorg". 
Error: Failed to send install Proposal or receive valid response from org exporterorg: Error: 14 UNAVAILABLE: Connect Failed
    at Client.newDefaultKeyValueStore.then.then.then (/home/hp/go/src/github.com/hyperledger/fabric/middleware/install-chaincode.js:136:10)
    at <anonymous>

--------------------------
CHAINCODE INSTALL FAILED: Error: Failed to send install Proposal or receive valid response from org exporterorg: Error: 14 UNAVAILABLE: Connect Failed
    at Client.newDefaultKeyValueStore.then.then.then (/home/hp/go/src/github.com/hyperledger/fabric/middleware/install-chaincode.js:136:10)
    at <anonymous>
--------------------------

Can we get any solution to above error.

Thank you.

**Comment by VRamakrishna** [comment]
It failed at the join, which then caused it to fail in the install. (Need to catch the join error and terminate the process right then, so there's a problem there. Can you open an issue for that?)

As for why this error occurred, can you first confirm that you are using Fabric version 1.1?

**Comment by prathapdheer** [comment]
Hi, I have the same issues. While installing the chaincode, I am encountering the same issue but a little bit different. Seeing that the discussion is still open, I was hoping you might be able to help me out.

2020-01-27T21:40:49.010Z - info: [ClientUtils]:

*******************************************************************************
*******************************************************************************
*
* Using temp dir: ../network/client-certs
*
*******************************************************************************
*******************************************************************************

(node:32529) DeprecationWarning: grpc.load: Use the @grpc/proto-loader module with grpc.loadPackageDefinition instead
Successfully extracted the config update from the configtx envelope
Successfully enrolled user 'admin' for exporterorg
Successfully signed config as admin of exporterorg
Successfully enrolled user 'admin' for importerorg
Successfully signed config as admin of importerorg
Successfully enrolled user 'admin' for carrierorg
Successfully signed config as admin of carrierorg
Successfully enrolled user 'admin' for regulatororg
Successfully signed config as admin of regulatororg
Successfully enrolled user 'admin' for every org and obtained channel config signatures
Successfully enrolled user 'admin' for orderer
Got genesis block. Channel tradechannel already exists
Successfully created the channel.
Successfully waited to make sure new channel was created.


--------------------------
CHANNEL CREATION COMPLETE
--------------------------


Joining channel tradechannel
Successfully enrolled 'admin' user for org exporterorg
Successfully got the genesis block
TypeError: client.newEventHub is not a function
    at Client.newDefaultKeyValueStore.then.then.then (/home/vagrant/go/src/trade-finance-logistics/middleware/join-channel.js:141:22)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
Joining channel tradechannel
Successfully enrolled 'admin' user for org importerorg
Successfully got the genesis block
TypeError: client.newEventHub is not a function
    at Client.newDefaultKeyValueStore.then.then.then (/home/vagrant/go/src/trade-finance-logistics/middleware/join-channel.js:141:22)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
Joining channel tradechannel
Successfully enrolled 'admin' user for org carrierorg
Successfully got the genesis block
TypeError: client.newEventHub is not a function
    at Client.newDefaultKeyValueStore.then.then.then (/home/vagrant/go/src/trade-finance-logistics/middleware/join-channel.js:141:22)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
Joining channel tradechannel
Successfully enrolled 'admin' user for org regulatororg
Successfully got the genesis block
TypeError: client.newEventHub is not a function
    at Client.newDefaultKeyValueStore.then.then.then (/home/vagrant/go/src/trade-finance-logistics/middleware/join-channel.js:141:22)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)


----------------------
CHANNEL JOIN COMPLETE
----------------------


Successfully enrolled user 'admin'
2020-01-27T21:40:55.888Z - error: [install-chaincode]: install proposal was bad from peer grpcs://localhost:7051 in org exporterorg
Failed to install chaincode in peers of organization "exporterorg". Error: Failed to send install Proposal or receive valid response from org exporterorg: Error: 2 UNKNOWN: chaincode error (status: 500, message: Error installing chaincode code tradecc:v0(chaincode /var/hyperledger/production/chaincodes/tradecc.v0 exists))
    at Client.newDefaultKeyValueStore.then.then.then (/home/vagrant/go/src/trade-finance-logistics/middleware/install-chaincode.js:136:10)
    at <anonymous>
2020-01-27T21:40:55.889Z - error: [install-chaincode]: Failed to install chaincode in peers of organization "exporterorg".
Error: Failed to send install Proposal or receive valid response from org exporterorg: Error: 2 UNKNOWN: chaincode error (status: 500, message: Error installing chaincode code tradecc:v0(chaincode /var/hyperledger/production/chaincodes/tradecc.v0 exists))
    at Client.newDefaultKeyValueStore.then.then.then (/home/vagrant/go/src/trade-finance-logistics/middleware/install-chaincode.js:136:10)
    at <anonymous>


--------------------------
CHAINCODE INSTALL FAILED: Error: Failed to send install Proposal or receive valid response from org exporterorg: Error: 2 UNKNOWN: chaincode error (status: 500, message: Error installing chaincode code tradecc:v0(chaincode /var/hyperledger/production/chaincodes/tradecc.v0 exists))
    at Client.newDefaultKeyValueStore.then.then.then (/home/vagrant/go/src/trade-finance-logistics/middleware/install-chaincode.js:136:10)
    at <anonymous>
--------------------------

I hope you can help me.
Thanks

**Comment by VRamakrishna** [comment]
@prathapdheer Please use the right version of Fabric and Fabric-CA. The `master` version of this repository works with Fabric `release-1.1`, and the other branches work with similarly named ones in the hyperledger repositories.

If you notice, I'd asked for a confirmation above, but that was never answered, which is why this issue remained open. But it's been a while, so I'm going to close it. These errors don't occur unless there is a version mismatch between the application code and the platform.
